version: '3.8'

services:
  fresh-market:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "3206:80"
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=10M
      - PHP_POST_MAX_SIZE=10M
    restart: unless-stopped
